/// <reference types="vite/client" />
// Browser demo for ts-hwp-transpiler.
//
// Split design:
//   * LEFT pane — preview rendered by `@rhwp/core`. The published wasm
//     engine handles layout, fonts, and page paginate; we just feed it
//     the bytes and concatenate the SVG each page emits. Building a
//     preview renderer ourselves would duplicate an already-published
//     Korean HWP stack, so we lean on it.
//   * RIGHT pane — Markdown rendered by this project's own wasm.
//     Structured MD export (stable ids, role/editable, domain hints)
//     is the differentiator, so that's what lives here.
//
// Both wasm engines parse the same bytes independently. No shared IR
// between them — they're different Rust crates compiled into separate
// wasm modules.

// @rhwp/core — preview engine. The bundled wasm asset is loaded as a
// URL so Vite serves it from the origin without an extra copy step.
import rhwpInit, { HwpDocument } from "@rhwp/core";
import rhwpWasmUrl from "@rhwp/core/rhwp_bg.wasm?url";

// Our own wasm — MD exporter. Generated by `npm run build:wasm`.
import init, {
  loadHwp,
  exportMarkdown,
  version,
} from "./wasm/hwp_transpiler_wasm.js";

// Register the browser-side text-measure callback BEFORE @rhwp/core
// initialises — rhwp's layout engine calls this synchronously from
// inside wasm to compute line breaks and justification spacing. Using
// a single cached Canvas2D context keeps the hot path allocation-free.
declare global {
  // eslint-disable-next-line no-var
  var measureTextWidth: (font: string, text: string) => number;
}

(() => {
  let ctx: CanvasRenderingContext2D | null = null;
  let lastFont = "";
  globalThis.measureTextWidth = (font: string, text: string): number => {
    if (!ctx) ctx = document.createElement("canvas").getContext("2d");
    if (!ctx) return text.length * 10;
    if (font !== lastFont) {
      ctx.font = font;
      lastFont = font;
    }
    return ctx.measureText(text).width;
  };
})();

const $ = <T extends HTMLElement = HTMLElement>(id: string): T =>
  document.getElementById(id) as T;

const fileInput = $<HTMLInputElement>("file");
const statusEl = $("status");
const previewEl = $("preview");
const previewMeta = $("preview-meta");
const markdownEl = $<HTMLPreElement>("markdown");
const copyBtn = $<HTMLButtonElement>("copy-md");

const llmModeEl = $<HTMLInputElement>("llm-mode");
const emitRolesEl = $<HTMLInputElement>("emit-roles");
const domainHintsEl = $<HTMLInputElement>("domain-hints");
const emitStylesEl = $<HTMLInputElement>("emit-styles");

// Most-recent parsed bytes — rhwp's HwpDocument is cheap to reconstruct
// and doesn't survive option changes gracefully, so we keep the raw
// bytes and re-parse when preview needs refreshing. Our own IR stays
// resident because we actually flip knobs against it on every render.
let lastBytes: Uint8Array | null = null;
let ourIr: unknown = null;

function setStatus(text: string, isError = false): void {
  statusEl.textContent = text;
  statusEl.classList.toggle("error", isError);
}

function renderPreview(bytes: Uint8Array): { pages: number; ms: number } {
  const started = performance.now();
  // HwpDocument's constructor is synchronous and parses immediately;
  // errors bubble up as wasm-thrown strings.
  const doc = new HwpDocument(bytes);
  const pages = doc.pageCount();
  const parts: string[] = [];
  for (let i = 0; i < pages; i++) {
    parts.push(doc.renderPageSvg(i));
  }
  previewEl.innerHTML = parts.join("\n");
  doc.free();
  return { pages, ms: Math.round(performance.now() - started) };
}

function renderMarkdown(ir: unknown): { bytes: number; ms: number } {
  const started = performance.now();
  const md = exportMarkdown(
    ir,
    llmModeEl.checked,
    emitRolesEl.checked,
    // editable tagging rides with roles — the CLI also emits them
    // together in practice.
    emitRolesEl.checked,
    domainHintsEl.checked,
    emitStylesEl.checked,
  );
  markdownEl.textContent = md;
  copyBtn.disabled = md.length === 0;
  return { bytes: md.length, ms: Math.round(performance.now() - started) };
}

function rerender(): void {
  if (!lastBytes || !ourIr) return;
  try {
    const p = renderPreview(lastBytes);
    previewMeta.textContent = `${p.pages} pages · ${p.ms}ms`;
    const m = renderMarkdown(ourIr);
    setStatus(
      `preview ${p.ms}ms · MD ${m.bytes.toLocaleString()} bytes / ${m.ms}ms`,
    );
  } catch (err) {
    setStatus(`render 실패: ${String(err)}`, true);
  }
}

async function handleFile(file: File): Promise<void> {
  setStatus(`읽는 중… ${file.name}`);
  const bytes = new Uint8Array(await file.arrayBuffer());
  try {
    ourIr = loadHwp(bytes);
  } catch (err) {
    setStatus(`loadHwp(ours) 실패: ${String(err)}`, true);
    ourIr = null;
    return;
  }
  lastBytes = bytes;
  rerender();
}

fileInput.addEventListener("change", () => {
  const f = fileInput.files?.[0];
  if (f) void handleFile(f);
});

document.body.addEventListener("dragover", (e) => e.preventDefault());
document.body.addEventListener("drop", (e) => {
  e.preventDefault();
  const f = e.dataTransfer?.files?.[0];
  if (f) void handleFile(f);
});

// Only MD-affecting knobs trigger rerender; they don't touch the
// preview since rhwp has no knobs exposed at this layer.
for (const el of [llmModeEl, emitRolesEl, domainHintsEl, emitStylesEl]) {
  el.addEventListener("change", () => {
    if (!ourIr) return;
    const m = renderMarkdown(ourIr);
    setStatus(`MD ${m.bytes.toLocaleString()} bytes / ${m.ms}ms`);
  });
}

copyBtn.addEventListener("click", async () => {
  const text = markdownEl.textContent ?? "";
  if (!text) return;
  try {
    await navigator.clipboard.writeText(text);
    copyBtn.textContent = "복사됨";
    setTimeout(() => (copyBtn.textContent = "복사"), 1200);
  } catch (err) {
    setStatus(`복사 실패: ${String(err)}`, true);
  }
});

// Boot both wasm engines in parallel. rhwp's init accepts a
// `module_or_path` telling it where to fetch its wasm binary; Vite's
// `?url` import gives us the hashed asset URL. Our own init discovers
// its wasm relative to the generated JS glue.
await Promise.all([init(), rhwpInit({ module_or_path: rhwpWasmUrl })]);
setStatus(
  `ready · ours ${version()} · @rhwp/core @${HwpDocument ? "0.7.x" : "?"}`,
);
